baseURL = "https://grosinger.net/"
languageCode = "en-us"
title = "Tony Grosinger"
publishDir = "../."
theme = "timeline"

[author]
  name = "Tony Grosinger"

[params]
  disableReadOtherPosts = true 
  enableSharingButtons = false

  [params.logo]
    logoText     = ""
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    logoCursorDisabled = true

  [[params.social]]
    name = "github"
    url = "https://github.com/tgrosinger"
    text = "Github"

  [[params.social]]
    name = "keybase"
    url = "https://keybase.io/tgrosinger"
    text = "Keybase"
    
 [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/tgrosinger"
    text = "LinkedIn"
